name: Unstable Build

on:
  workflow_dispatch:

jobs:
#   hub_build:
#     name: Build for Docker Hub
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v3

#       - name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v2
#         with:
#           platforms: linux/amd64,linux/arm64

#       - name: Sign in to Docker Hub
#         uses: docker/login-action@v2
#         with:
#           username: ${{ github.repository_owner }}
#           password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

#       - name: Create image tags
#         id: dockerinfo
#         run: |
#           echo "tagunstable=${{ github.repository_owner }}/insights-bot:unstable" >> $GITHUB_OUTPUT

#       - name: Build and Push
#         uses: docker/build-push-action@v4
#         with:
#           context: ./
#           file: ./Dockerfile
#           push: true
#           no-cache: false
#           tags: |
#             ${{ steps.dockerinfo.outputs.tagunstable }}

  ghcr_build:
    name: Build for GitHub Container Registry
    permissions:
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - # Add support for more platforms with QEMU (optional)
        # https://github.com/docker/setup-qemu-action
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64

      - name: Sign in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create image tags
        id: dockerinfo
        run: |
          echo "tagunstable=ghcr.io/${{ github.repository }}:unstable" >> $GITHUB_OUTPUT

      - name: Build and Push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          context: ./
          file: ./Dockerfile
          push: true
          no-cache: false
          tags: |
            ${{ steps.dockerinfo.outputs.tagunstable }}

      - name: Build installer
        run: |
          make build-installer IMG=ghcr.io/${{ github.repository }}:unstable

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: ollama-operator-installer-unstable
          path: dist/install.yaml

